### ISSUE TITLE
Source Code and Datasets

### ISSUE THREAD

**Issue by DoongLi** [KojiTakeda00/Small_object_change_detection#1]
Hi, will the dataset and source code of this paper be open source?

**Comment by KojiTakeda00** [comment]
Sorry for the delay in replying.
Unavoidable circumstances have arisen that prevent us from releasing the data and code to the public.

**Comment by GRF-Sunomikp31** [comment]
You mean the code will never open source？

**Comment by DoongLi** [comment]
You mean the code will never open source？

**Comment by KojiTakeda00** [comment]
Yes. There are no plans to make it open source in the future.

**Comment by DoongLi** [comment]
Ok, thx for your reply~
